version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (none needed for static site)"
  build:
    commands:
      - echo "Build phase complete. Copying files to artifacts."

artifacts:
  files:
    - '**/*'
  discard-paths: no
